### ISSUE TITLE
Even though it's just for show, should we add a <form> to create an account and one for "a login simulation?"

### ISSUE THREAD

**Issue by cellarstun** [lunartear/lunartear.github.io#2]
This site is just for show and has no active database, but maybe it'd be cool to have a sub-page to create an account or to log into one. It's not gonna work, but it'll look like an actual form.

**Comment by ohoiokab** [comment]
Sure, that'd be awesome!

**Comment by cellarstun** [comment]
A'ight, I'll commit the changes once I'm done.

**Comment by ohoiokab** [comment]
## Please make sure to use the proper German words:

**Email address:** `E-Mail-Adresse`
**Password**: `Passwort` (or _Kennwort_ – old word)
**Repeat password**: `Passwort wiederholen` (or _Kennwort wiederholen_)

**Comment by Kyoryuuu** [comment]
Thanks for uploading the code files.

We linked and uploaded the HTML files to the main repo.
